name: Continous Integration for yGuard

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: gradle check
