name: Continous Integration for yGuard

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
        sudo apt install -y gradle
        gradle wrapper
        ./gradlew wrapper --gradle-version 5.6.2
        ./gradlew check
